version: '3.9'

services:
  centos:
    build:
      context: .
    volumes:
      - ./enventory.sh:/home/enventory.sh
      - ./script-lab-4.sh:/home/script-lab-4.sh
      - ./screen.png:/home/screen.png
      - ./script-lab-5.sh:/home/script-lab-5.sh
    devices:
      - /dev/mem:/dev/mem
    cap_add:
      - ALL
    privileged: true
