version: '3.9'

services:
  centos:
    build:
      context: .
    volumes:
      - ./enventory.sh:/home/enventory.sh
    devices:
      - /dev/mem:/dev/mem
    cap_add:
      - ALL
    privileged: true
